# intra.yaml

train_dataset: DCLN       # Name of the training dataset
val_dataset: DCLN         # Name of the validation dataset
train_len: 160                # Length of training data (in frames)
val_len: 10                   # Length of validation data (in seconds)
epochs: 20                    # Number of training epochs
batch_size: 4                 # Batch size
scene: ['Raw', 'Raw']         # Different scenes in dataset, [0] for training, [1] for validation
nw: 0                         # Number of workers for data loading (recommend >0 to speed up)
lr: 5e-5                      # Initial learning rate
lrf: 0.01                     # Final learning rate factor (for learning rate decay)
optimizer: adamw              # Optimizer type, e.g., adam, adamw, sgd
model_name: TSCAN           # Model architecture name
weight_path: best             # Path to model weights; 'best' for best weights, 'last' for latest
device: cuda:0                # Device to run on (e.g., cuda:0, cuda:0,1 or cpu)
aug: TH                       # Data augmentation method tag
seed: 42                      # Random seed for reproducibility
loss_name: NegPearson         # Loss function name
plot: blandaltman             # Visualization type: wave, blandaltman, or both
plot_path: result/Plots       # Path to save visualization figures
hr_method: FFT                # Method to calculate heart rate: FFT or Peak
